name = "systemfd"
version = "0.1.0"
defaultTargets = ["systemfd"]

[[require]]
name = "lean-subst"
scope = "amarmaduke"
git = "https://github.com/amarmaduke/lean-subst"
rev = "49a61b2"

[[require]]
name = "lailac"
scope = "amarmaduke"
git = "https://github.com/amarmaduke/lilac"
rev = "951dadc"

[[lean_lib]]
name = "Core"

[[lean_lib]]
name = "Surface"

[[lean_lib]]
name = "Translation"

# [[lean_lib]]
# name = "SystemFD"

[[lean_exe]]
name = "systemfd"
root = "Main"
